### PR TITLE
A simple composer.json file ...

### PR DESCRIPTION
**Pull request by medienverbinder**
A simple composer.json file to support the PHP Package Repository Packagist.org.

[Review on Reviewable](https://reviewable.io/reviews/rugk/threema-msgapi-sdk-php/17)

### CODE REVIEW

**Comment by rugk** [comment]
The autoload is a bit confusing - I mean we can also autoload `threema_msgapi.phar` with the same effect.
But AFAIK `threema_msgapi.phar` should not be used here as it is just the packed version of everything. Am I right?

Secondly what about adding a "provides" entry? Because as this is an SDK it provides access to Threema Gateway and other libraries may depend on it.
I think that is what provides is intended to do.



---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[composer.json, line 4 [r1]](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17#-K2liF4yzoFw9MApiUuO)** ([raw file](https://github.com/rugk/threema-msgapi-sdk-php/blob/1ebc640bee60a983537af280a48e04315e74f906/composer.json#L4)):</sup>
Please add the missing a in Threem_a_ and please call it "Threema PHP-SDK" or something similar as it is not the code of the Threema app. ("Threema source code") :wink: 
Additionally the "successfully" is a unnecessary IMO. I mean obviously it depends whether it is successfully, so the description should be neutral and do not have such a word.

Additionally consider removing "This is a fork of the original repo after it was announced that it is no longer maintained by Threema.". This is mostly only interesting for visitors of the repo and if you do not read it correctly you may think that it means this is discontinued by Threema, but that's not true as they just do not host it at GitHub any more.
I'd suggest to include a small explanation of what you can do with this package (send (sensitive) message/files/... (securely), probably mention some thing where it can be used like TAN, OTP and so on. Let you inspire from the Threma Gateway hompage. :smiley: 



---

<sup>**[composer.json, line 5 [r1]](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17#-K2lm4kmJjRa6p0Rc_1W)** ([raw file](https://github.com/rugk/threema-msgapi-sdk-php/blob/1ebc640bee60a983537af280a48e04315e74f906/composer.json#L5)):</sup>
A `"` is missing



---

<sup>**[composer.json, line 6 [r1]](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17#-K2lm7InURcrTudnfID1)** ([raw file](https://github.com/rugk/threema-msgapi-sdk-php/blob/1ebc640bee60a983537af280a48e04315e74f906/composer.json#L6)):</sup>
Possibly add some more keywords: encrypted/secure/end-to-end-encrypted, Switzerland, Gateway, ...



---

<sup>**[composer.json, line 7 [r1]](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17#-K2lmpHNwPx4UhjyD6uN)** ([raw file](https://github.com/rugk/threema-msgapi-sdk-php/blob/1ebc640bee60a983537af280a48e04315e74f906/composer.json#L7)):</sup>
What do you think about using https://rugk.github.io/threema-msgapi-sdk-php/ instead?
Or - which would be better - to add https://rugk.github.io/threema-msgapi-sdk-php/ as a documentation. Is there an entry "doc" or similar possible?



---

<sup>**[composer.json, line 9 [r1]](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17#-K2lnB8jA3K_Pf-Ydzqt)** ([raw file](https://github.com/rugk/threema-msgapi-sdk-php/blob/1ebc640bee60a983537af280a48e04315e74f906/composer.json#L9)):</sup>
May add:

``` json
{
        "name": "Threema GmbH",
        "email": "support-gateway-service@threema.ch"
},
```

See https://gateway.threema.ch/en/contact



---

<sup>**[composer.json, line 15 [r1]](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17#-K2lnkaOTHPyU0g5BkYd)** ([raw file](https://github.com/rugk/threema-msgapi-sdk-php/blob/1ebc640bee60a983537af280a48e04315e74f906/composer.json#L15)):</sup>
PHP version is correct, ...
but the requirements of Threema are a special thing...
So it would be good if we could define it like this:
`libsodium-php OR (64bit php)`

Related: libsodium-php/issues/68
Example: https://github.com/paragonie/halite/blob/4cd2debc6dd2bd9ca3e87374750fa60c67f8d712/composer.json#L7



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17)

**Comment by rugk** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[composer.json, line 15 [r1]](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17#-K2lnkaOTHPyU0g5BkYd)** ([raw file](https://github.com/rugk/threema-msgapi-sdk-php/blob/1ebc640bee60a983537af280a48e04315e74f906/composer.json#L15)):</sup>
Wrong link: https://github.com/jedisct1/libsodium-php/issues/68



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17)

**Comment by rugk** [comment]
Also I might make you aware you want to merge this into `official`. I would rather prefer to not adjust the official branch and merge all changes into master.

---

Please also add `"license": "MIT"`.

**Comment by medienverbinder** [comment]
Thanks for the feedback via reviewable.io. Let's see ...

**Comment by rugk** [comment]
> The autoload is a bit confusing - I mean we can also autoload threema_msgapi.phar with the same effect.
> But AFAIK threema_msgapi.phar should not be used here as it is just the packed version of everything. Am I right?

Okay, so I've decided this for me now. We'll remove the phar from the repo in the near future. Files buildable from the source should not be included in the repo anyway.



---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[composer.json, line 15 [r1]](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17#-K2lnkaOTHPyU0g5BkYd)** ([raw file](https://github.com/rugk/threema-msgapi-sdk-php/blob/1ebc640bee60a983537af280a48e04315e74f906/composer.json#L15)):</sup>
FYI it seems you can also use "suggest" to suggest additions. So adding this too would be nice, because we highly suggest to install libsodium - even you use a 64bit PHP version.

About the issue [I linked](https://github.com/jedisct1/libsodium-php/issues/68): Ignore it - as you can see it is now closed. Just add libsodium as a requirement like shown in the example.
And as it seems you can require 64bit php [also easily](https://stackoverflow.com/questions/19461262/composer-can-i-pick-a-package-based-on-the-processor-architecture-32bit-vs-64b#answer-19465340).



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17)

**Comment by rugk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17)

**Comment by medienverbinder** [comment]
But for a correct definition of the requirements we need a "or" condition:

"php-64bit": ">=5.4.0"

OR

"php": ">=5.4.0" AND "ext-libsodium": "^1.0.2"

Mhhh.....do you know how that is defined in a composer.json file?

**Comment by rugk** [comment]
> Mhhh.....do you know how that is defined in a composer.json file?

I've seen `|` in some examples. However in the doc I can only find it here: https://getcomposer.org/doc/04-schema.md#conflict

However I think `|`should be possible.

**Comment by rugk** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[composer.json, line 7 [r1]](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17#-K2lmpHNwPx4UhjyD6uN)** ([raw file](https://github.com/rugk/threema-msgapi-sdk-php/blob/1ebc640bee60a983537af280a48e04315e74f906/composer.json#L7)):</sup>
BTW you can add "docs" under "support": https://stackoverflow.com/questions/33637479/can-i-add-a-documentation-link-to-composer/33637941



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17)

**Comment by medienverbinder** [comment]
Composer conflict: "Lists packages that conflict with this version of this package. They will not be allowed to be installed together with your package." 

I'm not sure if conditional requirements could be implemented ... I have to read again :-)

Or just so .... but that is no solution :-(

``` javascript
"require": {
  "php-64bit": ">=5.4.0"
},
"suggest": {
  "ext-libsodium": "^1.0.2"
},
```

**Comment by rugk** [comment]
With a  quick research the only thing I could find about conditional things in composer is this: https://github.com/composer/composer/issues/3618

BTW you do not have to require libsodium v1.0.2 as [this SDK also supports older versions of lubsodium](https://github.com/rugk/threema-msgapi-sdk-php/blob/master/source/Threema/MsgApi/Tools/CryptToolSodiumDep.php). However you may suggest the newest version of the library of course.

**Comment by rugk** [comment]
About the conditional thing [I've now asked on Stackoverflow](https://stackoverflow.com/questions/33706986/how-can-i-use-conditional-or-in-requirements-in-a-composer-json).

**Comment by rugk** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[composer.json, line 4 [r1]](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17#-K2liF4yzoFw9MApiUuO)** ([raw file](https://github.com/rugk/threema-msgapi-sdk-php/blob/1ebc640bee60a983537af280a48e04315e74f906/composer.json#L4)):</sup>
Okay, you've removed the text. So now adding a small explanation of this library again would be nice.



---

<sup>**[composer.json, line 9 [r1]](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17#-K2lnB8jA3K_Pf-Ydzqt)** ([raw file](https://github.com/rugk/threema-msgapi-sdk-php/blob/1ebc640bee60a983537af280a48e04315e74f906/composer.json#L9)):</sup>
You can still leave the homepage and mail here too. IMO it is no problem to add this redundantly - it just shows that this is the same person/.... 



---

<sup>**[composer.json, line 15 [r1]](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17#-K2lnkaOTHPyU0g5BkYd)** ([raw file](https://github.com/rugk/threema-msgapi-sdk-php/blob/1ebc640bee60a983537af280a48e04315e74f906/composer.json#L15)):</sup>
Okay, so we only have to solve the issue with the `OR` which would be needed here: https://stackoverflow.com/questions/33706986/how-can-i-use-conditional-or-in-requirements-in-a-composer-json



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17)

**Comment by medienverbinder** [comment]
Furthermore, I have asked the support which libsodium version must be installed at least. With the response we can consider a minimum libsodium version in the composer.json file.

**Comment by rugk** [comment]
AFAIK it supports all libsodium versions. Even [< v0.2](https://github.com/rugk/threema-msgapi-sdk-php/blob/master/source/Threema/MsgApi/Tools/CryptToolSodiumDep.php) (although that is of course not recommend and support for this version may be removed in the future).
[This](https://github.com/rugk/threema-msgapi-sdk-php/blob/master/source/Threema/MsgApi/Tools/CryptTool.php#L64-L84) is the method which decides what CryptTool (libsodium, Salt, ...) will be used and as you can see there it just does a feature check (it checks [whether a method provided by the old libsodium library can be used](https://github.com/rugk/threema-msgapi-sdk-php/blob/master/source/Threema/MsgApi/Tools/CryptToolSodium.php#L108-L115) - because the new version uses [a namespace](https://github.com/jedisct1/libsodium-php/commit/7b5d819e2f35953ea46a8bc360341177cf90dd50) (added in https://github.com/jedisct1/libsodium-php/pull/30) and only if this fails it falls back to the old libsodium integration as a class.

**Comment by rugk** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[composer.json, line 15 [r1]](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17#-K2lnkaOTHPyU0g5BkYd)** ([raw file](https://github.com/rugk/threema-msgapi-sdk-php/blob/1ebc640bee60a983537af280a48e04315e74f906/composer.json#L15)):</sup>
It seems we can fix the special requirements with a script executed after the installation of a library: https://stackoverflow.com/questions/33706986/using-conditional-or-in-requirements-in-a-composer-json/33711530#vote-accepted-33711530
Although this is not the nicest solution either.

However for now you can just add a recent libsodium version as a suggested one and we may add the 64bit script check later.
Possibly we can also just suggest x64 bit PHP, but include a description that this is only required when Salt function is used.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17)

**Comment by rugk** [comment]
BTW if you add me as a contributor to your fork I can push some changes to your branch and help making the changes I think of.

**Comment by medienverbinder** [comment]
Hi,

Threema support recommends the first stable version libsodiom (1.0.0 ). The libsodium dependence of the php variants is a small problem ,in fact . Composer does not support "or" conditions on an easy way. I am a bit short of time and I've added your username as a collaborator for this fork.

**Comment by rugk** [comment]
So I've changed all things I commented on reviewable.io.
Do you have any further suggestions or do you think now it can be merged?

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[composer.json, line 15 [r1]](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17#-K2lnkaOTHPyU0g5BkYd:-K3dexvMOUj8PLkchEB-:-461176785) ([raw file](https://github.com/rugk/threema-msgapi-sdk-php/blob/1ebc640bee60a983537af280a48e04315e74f906/composer.json#L15)):_
Okay, basically I now followed [this](https://stackoverflow.com/questions/33706986/using-conditional-or-in-requirements-in-a-composer-json/33711530#answer-33744539) and just used a simple way.
I clearly added an explanation of the problem and made sure libsodium is suggested in a very obtrusive way. And if a user should really decline to install libsodium on a 32bit system the SDK will throw an error anyway.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rugk/threema-msgapi-sdk-php/17#-:-K3dijA6X54KxJZ8LxIY:1251581845)_

**Comment by medienverbinder** [comment]
O.k. Nice! I have nothing to add. For me, everything looks good. Thank You!

**Comment by rugk** [comment]
You're welcome!
So as this Pull Request is still on the wrong branch I opened a new [Pull Request](https://github.com/rugk/threema-msgapi-sdk-php/pull/20) to add it to the right branch.

Next time just make sure you use a new branch (like `patch-feature`) in your fork of this repo and create a PR which merges changes to `master` and not `official` [as explained in the wiki](https://github.com/rugk/threema-msgapi-sdk-php/wiki/Branches-and-releases).

**Pull request closed without merging**
